### ISSUE TITLE
4.0.0 Version crashes for some instances (Windows 10)

### ISSUE THREAD

**Issue by benjaminbartsch** [sfiruch/kissat#7]
See here:

[timetable_73MB.zip](https://github.com/user-attachments/files/16509190/timetable_73MB.zip)

![grafik](https://github.com/user-attachments/assets/1b1bb931-d6ee-4f65-b240-41709df3dbd0)

**Comment by benjaminbartsch** [comment]
Smaller instances are working fine.

**Comment by benjaminbartsch** [comment]
@sfiruch: 

> I think it'd make sense to discuss Windows-specific bugs in the repo of the fork. Also, can you test whether disabling shrinking helps?

How do I disable it?

**Comment by benjaminbartsch** [comment]
![grafik](https://github.com/user-attachments/assets/276e828e-6433-4b02-88a5-61ea78825973)

if it is shrink=0, then it dows not work

**Comment by benjaminbartsch** [comment]
With verbose=3 one can see this:

![grafik](https://github.com/user-attachments/assets/2f061989-b263-4459-9968-12ba96c16fa6)

**Comment by benjaminbartsch** [comment]
It seems to work with

`--congruence=false`

**Comment by benjaminbartsch** [comment]
It also works with:
`--congruencebinaries=false`

**Comment by sfiruch** [comment]
Thanks for reporting this. I provided updated binaries, which should solve the problem.

Root cause is/was that the Radix sort does stack allocation, which is limited to 1MB by default (which is a sensible limit). I changed the code to do heap allocations instead. In my experiments I didn't measure any negative performance effects.

**Comment by benjaminbartsch** [comment]
wow, thank you for that quick analysis and fixing!
